In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data/pollution_us_2000_2016.csv', encoding='utf8', engine='python')
data = data.drop(data.columns[0], axis=1)
data = data.fillna(data.groupby(['Date Local', 'County Code']).transform('mean'))

In [3]:
data.to_csv('data/prepocessed.csv', ',', encoding='utf8')
data.head()

,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,NO2 Mean,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,19.041667,...,Parts per billion,3.000000,9.0,21,13.000000,Parts per million,1.145833,4.2,21,13.666667
1,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,19.041667,...,Parts per billion,3.000000,9.0,21,13.000000,Parts per million,0.878947,2.2,23,25.000000
2,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,19.041667,...,Parts per billion,2.975000,6.6,23,5.333333,Parts per million,1.145833,4.2,21,13.666667
3,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,19.041667,...,Parts per billion,2.975000,6.6,23,5.333333,Parts per million,0.878947,2.2,23,25.000000
4,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-02,Parts per billion,22.958333,...,Parts per billion,1.958333,3.0,22,4.000000,Parts per million,0.850000,1.6,23,11.666667